"""Two real Meta operations on frozen T0/T1 evidence; no Task side effects."""
import json, sys, time
from pathlib import Path
from dataclasses import asdict

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from sia.task_meta.pipeline import backend_for, load_config
from sia.task_meta.meta import MetaAgent, experience_input, validate_meta_candidate
from sia.task_meta.meta_harness.five_stage import paired_outcome, materialize
from sia.task_meta.durable import load_task, task_hash
from sia.task_meta.types import MetaAgentState, ImprovementExperience, FiveStageMetaUpdate, EvaluationResult
from sia.task_meta.observations import build_observation
from sia.task_meta.updaters import updater_capabilities
from sia.task_meta.storage import save_json

run=Path(sys.argv[1]);source=Path(sys.argv[2]);config=load_config(ROOT/'configs/meta-reload-only.json')
def read(p):return json.loads(p.read_text())
status={'scope':'real_self_update_then_real_routing_only','started_at':time.time(),'API_cost_usd':None,
        'source_run':str(source),'Task_rollouts':0,'SFT_steps':0,'historical_budget_preserved':True}
def phase(value,**kwargs):
    status.update(phase=value,**kwargs);save_json(run/'status.json',status);print(json.dumps(status),flush=True)
try:
    client,store,g0=backend_for(config,run)
    meta=MetaAgentState(config.meta.model,str(g0.path/'instructions.md'),g0.version,g0.hash,str(g0.path))
    task=load_task(read(source/'gen_1/task_state.json'))
    task_out=load_task(read(source/'gen_1/task_state_after_rollout.json'))
    experience=ImprovementExperience(**read(source/'gen_1/improvement_experience.json'))
    outcome=paired_outcome(run/'evidence',experience)
    assert outcome['denominator']==10 and abs(outcome['partial_score_comparison']['mean_delta']+.13799)<1e-9
    envelope=experience_input(experience,[experience],task)
    envelope['outcome_review']=outcome
    envelope['instruction']=(ROOT/'meta_harness/mandatory_meta_self_update.md').read_text() + '\nExecution focus: Produce ONE minimal evidence-grounded procedural G change and its principle operation. Inspect only the relevant existing rule and required schema. Prefer one concise rule/instruction change when sufficient; do not rewrite unrelated policies. Use one batched inspection, then construct the candidate and run the available validator. The next real routing must apply the new rule and cite its active principle ID. Do not prescribe its M/H/A choice.' 
    prior_candidate = read(ROOT/'meta_harness/previous_native_candidate.json')
    envelope['native_candidate_repair'] = prior_candidate
    envelope['instruction'] += (
        '\nTARGETED REPAIR OF YOUR EARLIER REAL NATIVE CANDIDATE: read meta_input/previous_native_candidate.json first. '
        'Its candidate was generated by the real experimental Meta on these same real paired observations; it has NOT been accepted. '
        'Reuse and repair its grounded lesson rather than restart evidence discovery. Inspect only what is needed to check the repairs. '
        'Known errors: (1) the final delivery must be ONLY the exact JSON receipt, no prose, and candidate_file must be .meta_candidate.json, not an absolute path; '
        '(2) evolution.json#/self_update/rules/first_turn_activation_audit is not a valid JSON pointer into an array: named rule IDs do not select array elements; '
        'bind a real changed target using an array index or the changed array itself, and make principle g_targets agree; '
        '(3) the old candidate only changes self_update behavior, whereas this validation requires the NEXT ROUTING to apply a new operative rule linked to the principle. '
        'Make the smallest justified common-instruction or routing-rule change that applies the lesson to next component selection, without prescribing M/H/A. '
        'Check its factual claims: aggregate train-plus-probe costs must not be labeled paired-probe costs; use the exact paired metrics in the supplied outcome. '
        'The old candidate also mistyped task_state_hash; copy all current identity values exactly, never retype hash text. Generate a NEW request-bound envelope with the current identity; old identities and hashes are provenance only. '
        'Do not rewrite the previous candidate input. Write the complete repaired .meta_candidate.json with native tools, hash it, return only the required receipt. '
        'Prefer one batched repair-and-validation command after reading the saved candidate.')
    envelope['instruction'] += ('\nThe previous_native_candidate.json file is now the ORIGINAL ENVELOPE directly: its result is at ["result"], not under another candidate wrapper. '
        'For the new envelope derive identity values from the current result_schema.json properties/const fields instead of typing hashes. '
        'No need to enumerate directories or print the full schema again: the exact input file names are already declared. Read the saved candidate, change the invalid binding plus next-routing effect, and write the candidate in a batched command. '
        'The final acknowledgement must contain only request_id, candidate_file=".meta_candidate.json", candidate_sha256, without surrounding prose.')
    envelope['instruction'] += ('\nThe exact allowed evidence IDs are in meta_input/allowed_evidence_ids.json, a JSON list derived by the controller. '
        'Do not search principle_contract.py for evidence values; it contains definitions, not the evidence list. '
        'Finish the existing candidate repair with the smallest grounded changes; the previous candidate is unaccepted input. '
        'If you need current envelope identities, read const values from meta_input/result_schema.json. '
        'Use native tools, then deliver only the exact receipt JSON. No separate design report is needed.')
    client.bind_context(run.name,1,task_hash(task))
    phase('self_update_running',g_before=g0.hash,version_before=g0.version)
    update=client.complete('Analyze the real transition and propose a justified G/K update.',FiveStageMetaUpdate,
        meta_state=meta,operation='learn',decision_id=experience.decision.get('decision_id'),
        experience_id=experience.experience_id,operation_input=envelope,
        validate_candidate=lambda candidate:validate_meta_candidate(candidate,meta))
    save_json(run/'self_update.json',update.model_dump(mode='json'))
    candidate_files,flags=materialize(update,g0.read_files())
    committed=store.commit_update(g0.hash,instruction_text=update.harness,
        file_updates={k:v for k,v in candidate_files.items() if k!='self_update_protocol.md'},
        request_id=update.request_id,experience_id=update.experience_id,phase='meta_self_update')
    current=store.active().verify()
    assert current.hash==committed.hash
    meta=MetaAgentState(config.meta.model,str(current.path/'instructions.md'),current.version,current.hash,str(current.path))
    save_json(run/'meta_state_after.json',asdict(meta))
    changed=[k for k,v in current.read_files().items() if v!=g0.read_files()[k]]
    phase('routing_running',self_update_status=update.status,g_after=current.hash,version_after=current.version,
          changed_files=changed,**flags)
    # A fresh backend instance must read the committed store, with no stale G cache.
    from sia.task_meta.meta_backends.codex_openrouter import CodexOpenRouterBackend
    fresh=CodexOpenRouterBackend(config.meta,run/'meta',store)
    fresh.bind_context(run.name,1,task_hash(task_out))
    result=EvaluationResult(read(source/'gen_1/results.json'),read(source/'gen_1/agent_execution.json'),
        cost=read(source/'gen_1/cost.json'),evaluated_state=task,output_artifacts=task_out.artifacts,
        artifact_provenance=read(source/'gen_1/artifact_provenance.json'),
        rollout_artifact_diff=read(source/'gen_1/rollout_artifact_diff.json'))
    capabilities={'trainer_configured':True,'sft_profile':'multidomain'}
    capabilities.update(updater_capabilities(task_out,result,True,sft_profile='multidomain'))
    observation=build_observation(task,task_out,meta,result,
        [read(source/f'gen_{i}/results.json') for i in range(2)],[experience],
        [read(source/f'gen_{i}/cost.json') for i in range(2)],capabilities,retain_raw=True)
    save_json(run/'routing_observation.json',asdict(observation))
    decision=MetaAgent(fresh,capabilities).diagnose_and_route(meta,observation)
    save_json(run/'routing_response.json',decision.model_dump(mode='json'))
    routing_calls=[]
    for path in (run/'meta/calls').glob('*/request.json'):
        request=read(path)
        if request['operation']=='routing':
            assert request['meta_harness_hash']==current.hash
            assert read(path.parent/'status.json')['state']=='META_COLLECTED'
            for name,content in current.read_files().items():
                loaded=path.parent/'workspace/meta_input/G'/name
                assert loaded.read_text()==content, name
            routing_calls.append(request['request_id'])
    assert routing_calls
    library=json.loads(current.read_files()['principles.json'])
    old_ids={p['principle_id'] for p in json.loads(g0.read_files()['principles.json'])['records'] if p['active']}
    new_ids={p['principle_id'] for p in library['records'] if p['active']}-old_ids
    used=set(decision.used_principle_ids)
    phase('completed',routing_action=decision.action.value,routing_request_ids=routing_calls,
        new_principles=sorted(new_ids),used_principle_ids=sorted(used),new_principles_used=sorted(new_ids&used),
        changed_G_loaded_in_real_routing=bool(changed),
        real_self_update_and_reuse_verified=bool(changed),
        performance_improvement_verified=False,ended_at=time.time())
except Exception as exc:
    phase('failed',error_type=type(exc).__name__,error=str(exc),ended_at=time.time())
    raise
